<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.wms</groupId>
        <artifactId>wms-server</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>wms-report</artifactId>
    <name>wms-report</name>
    <description>统计报表模块</description>

    <dependencies>
        <dependency>
            <groupId>com.wms</groupId>
            <artifactId>wms-common</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.wms</groupId>
            <artifactId>wms-business</artifactId>
        </dependency>
        <dependency>
            <groupId>com.wms</groupId>
            <artifactId>wms-item</artifactId>
        </dependency>
        <dependency>
            <groupId>com.wms</groupId>
            <artifactId>wms-warehouse</artifactId>
        </dependency>
        <dependency>
            <groupId>com.wms</groupId>
            <artifactId>wms-system</artifactId>
        </dependency>
        <dependency>
            <groupId>com.itextpdf</groupId>
            <artifactId>kernel</artifactId>
            <version>${itext.version}</version>
        </dependency>
        <dependency>
            <groupId>com.itextpdf</groupId>
            <artifactId>layout</artifactId>
            <version>${itext.version}</version>
        </dependency>
    </dependencies>
</project>
